### ISSUE TITLE
Chaostoolkit issue.

### ISSUE THREAD

**Issue by SidGrundfos** [chaostoolkit-incubator/chaostoolkit-humio#4]
What do I need to do to log to Humio?
I have the following info - 
"Humio": {
    "Token": "3QHlnjdIajQw60164iBWYaXV3Dcs0V0l6bmveMTJjCQt",
    "http": "https://cloud.humio.com/api/v1/dataspaces/gic/ingest/elasticsearch"
  }

I have added the follwoing -

**Comment by Lawouach** [comment]
Hello,

I hope the token you copied is not the real one? Otherwise I would suggest you regenerate it right away.

If you want to hardcode the values:

```
"secrets": {
        "humio": {
            "token": "3Q..."
            "dataspace": "gic"
        }
    },```

If you want to depend on env variable:

```
"secrets": {
        "humio": {
            "token": {
                "type": "env",
                "key": "HUMIO_INGEST_TOKEN"
            },
            "dataspace": {
                "type": "env",
                "key": "HUMIO_DATASPACE"
            }
        }
    },```

and set the env as follows:

```
$ export HUMIO_INGEST_TOKEN=3Q...
$ export HUMIO_DATASPACE=gic
```

**Comment by SidGrundfos** [comment]
it still says missing Humio secret
![image](https://user-images.githubusercontent.com/53938860/67770933-9fb44100-fa57-11e9-8144-a08e2cb91dba.png)

**Comment by SidGrundfos** [comment]
Do I need to add something else at someplace else?

**Comment by Lawouach** [comment]
mmmh, weird. Could you show me the experiment fully? (Removing all sensitive info)

**Comment by SidGrundfos** [comment]
{
    "title":"Checks if the given app is running",
    "name": "all-our-microservices-should-be-healthy",
    "description": "If a pod not running gives health",
    "steady-state-hypothesis":{
        "title":"test running pods",
        "secrets": {
            "humio": {
                "token": "...",
                "dataspace": "gic"
            }
        },
        "controls": [
            {
                "name": "humio-logger",
                "provider": {
                    "type": "python",
                    "module": "chaoshumio.control",
                    "secrets": ["humio"]
                }
            }
        ],
        "probes":[
            {
                "name": "count-pods",
                "type": "probe",
                "tolerance": 7,
                "provider": {
                  "func": "count_pods",
                  "arguments": {
                    "ns": "wwnc",
                    "label_selector": ""
                  },
                  "type": "python",
                  "module": "chaosk8s.pod.probes"
                }
            },
            {
                "type": "probe",
                "name": "all-services-are-healthy",
                "tolerance": true,
                "provider": {
                    "type": "python",
                    "module": "chaosk8s.probes",
                    "func": "all_microservices_healthy"
                }
            },
            {
                "type": "probe",
                "name": "we-can-request-service",
                "tolerance": 200,
                "provider": {
                    "type": "http",
                    "timeout": 3,
                    "verify_tls": false,
                    "url": "..."
                }
            },
            {
                "name": "Network-microservice-available-and-healthy",
                "type": "probe",
                "tolerance": true,
                "provider": {
                  "func": "microservice_available_and_healthy",
                  "arguments": {
                    "ns":"wwnc",
                    "name":"grundfosgicwwncnetworkapi"
                  },
                  "type": "python",
                  "module": "chaosk8s.probes"
                }
            }
            ,
            {
                "name": "ProxyApi-microservice-available-and-healthy",
                "type": "probe",
                "tolerance": true,
                "provider": {
                  "func": "microservice_available_and_healthy",
                  "arguments": {
                    "ns":"wwnc",
                    "name":"grundfosgicwwncapi"
                  },
                  "type": "python",
                  "module": "chaosk8s.probes"
                }
            }
            ,
            {
                "name": "Data-microservice-available-and-healthy",
                "type": "probe",
                "tolerance": true,
                "provider": {
                  "func": "microservice_available_and_healthy",
                  "arguments": {
                    "ns":"wwnc",
                    "name":"grundfosgicwwncdataapi"
                  },
                  "type": "python",
                  "module": "chaosk8s.probes"
                }
            }
        ]
    },
    "method":[
        {
            "type": "action",
            "name": "terminate-db-pod",
            "provider": {
                "type": "python",
                "module": "chaosk8s.pod.actions",
                "func": "terminate_pods"
            },
            "pauses": {
                "after": 5
            }
        }
    ]
}

**Comment by Lawouach** [comment]
The mistake comes from the fact you declared the secrets at the wrong level. They should not be a child of `"steady-state-hypothesis"` but a sibling.

**Comment by SidGrundfos** [comment]
works fine, thanks a bunch :)
