### ISSUE TITLE
Remove dataspace parameter and parametize URL

### ISSUE THREAD

**Issue by mwl** [chaostoolkit-incubator/chaostoolkit-humio#7]
As per [our conversation](https://chaostoolkit.slack.com/archives/C9BS95CQM/p1578750085003900).

The `dataspace` (which now is called a repository) is not used anymore.
https://github.com/chaostoolkit-incubator/chaostoolkit-humio/blob/e7757200d9b9844135fddd8cefd74af2465a5e63/chaoshumio/__init__.py#L34-L37

The `url` var
https://github.com/chaostoolkit-incubator/chaostoolkit-humio/blob/e7757200d9b9844135fddd8cefd74af2465a5e63/chaoshumio/__init__.py#L44-L46
should be expose to the user for on-prem installation.
The new repository/dataspace-less url is [`/api/v1/ingest/humio-ingest`](https://docs.humio.com/api/ingest/#structured-data).

My suggestion is to replace parametrize the `https://cloud.humio.com` part of the current `url` var and completely ignore `dataspace`.

**Comment by russmiles** [comment]
@mwl are there likely to be deployments of Humio out there that _will_ need the dataspace parameter? Should we remove the necessity for it to be provided as a secret, but still look to support it if present for backwards compatibility?

**Comment by russmiles** [comment]
@mwl should we default to `https://cloud.humio.com` still if no `HUMIO_URL` (or whatever we call it, see previous question) is specified?

**Comment by mwl** [comment]
> @mwl are there likely to be deployments of Humio out there that _will_ need the dataspace parameter?

… Not that we support.

> Should we remove the necessity for it to be provided as a secret, but still look to support it if present for backwards compatibility?

I'd say it's a wasted effort. It's been out for so long now that it's unlikely that anyone will need it.

**Comment by russmiles** [comment]
So is destination repository/dataspace now selected elsewhere, all we need is to specify the token and get the right url for the humio service? Just checking I understand correctly @mwl
